### PR TITLE
Adding the ability to install extension with cocoapods

### PR DESCRIPTION
**Pull request by MikeSilvis**

### CODE REVIEW

**Comment by iyegoroff** [comment]
Thanks for contribution. Is this considered to be a step for the `Mostly automatic installation` or it is a standalone approach?

**Comment by MikeSilvis** [comment]
@iyegoroff yes, this is a `mostly automatic installation` and it does not require linking the libraries like shown in your instructions. This is common practice of various other linking libraries and you can see it here: https://github.com/react-native-community/react-native-linear-gradient#cocoapods

**Comment by iyegoroff** [comment]
There was a build error when I tried to compile MatrixFilterConstructor example. I have added a fix for this error [here](https://github.com/iyegoroff/react-native-color-matrix-image-filters/commit/d413d2c04d117dcf5107e19aaff7ac78ddfabdb1) - please, confirm that you can install the module with Cocoapods and compile it successfully after my patch.

**Comment by MikeSilvis** [comment]
@iyegoroff yup! That worked! Thanks

**Comment by iyegoroff** [comment]
published v1.0.5

**Pull request merged**
